version: '3.3'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/
    networks:
      - container-link

  web:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/srv/aws-educate:cached
      - rbenv_dir:/usr/local/rbenv
    ports:
      - 3000:3000
    networks:
      - container-link
    environment:
      - VIRTUAL_HOST=elemental-lab.jp
      - LETSENCRYPT_HOST=elemental-lab.jp
      - LETSENCRYPT_EMAIL=abe@strategy-jp.com
      - LETSENCRYPT_TEST=false
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  rbenv_dir:
    driver: local

networks:
  default:
    external:
      name: bridge
  container-link:
  #   name: container_network